### ISSUE TITLE
History of Durham restaurants should be an H1 or H2

### ISSUE THREAD

**Issue by kostajh** [savaslabs/durham-restaurants-map#7]

**Comment by timstallmann** [comment]
@kostajh I pushed a branch with this as an h3 if you want to check it out, but really anything bigger than p and we start losing a lot of valuable screen real estate, which I think the map should really foreground.

**Comment by kostajh** [comment]
@timstallmann it's more for the structure of the page, which should have an H1 describing what the page is about (for search engines) and accessibility, although the latter isn't as much of a concern here since we've got a map that's all of the page content. Can we do an inline style to make the H1 a smaller style?

**Comment by timstallmann** [comment]
sure, no prob!
